### ISSUE TITLE
Client Crashing

### ISSUE THREAD

**Issue by vertex101** [Pack4Duck/ClassicUO#1603]
**Describe the bug**

i was logged into a server and then i logged out to do something around the house and when i came back to get on the client is just crashing

**To Reproduce**

it happens when i login and click on my character on to go into the world

**Expected behavior**

**Screenshots**

`
######################## [START LOG] ########################
ClassicUO [STANDARD_BUILD] - 0.1.11.59 - 03/08/2023 04:14:47
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Shard: MysticalUnicornThe2ndComing.fantasyleague.cc
ClientVersion: 4.0.11c

Exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.ThrowHelper.ThrowIndexOutOfRangeException()
   at ClassicUO.Network.Huffman.DecompressChunk(Span`1 src, Int32& srcOffset, Int32 srcLength, Span`1 dest, Int32 destOffset, Int32& destLength)
   at ClassicUO.Network.NetClient.DecompressBuffer(Span`1 buffer, Int32& length)
   at ClassicUO.Network.NetClient.ProcessRecv()
   at ClassicUO.Network.NetClient.Update()
   at ClassicUO.GameController.OnNetworkUpdate()
   at ClassicUO.GameController.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.RunLoop()
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Client.Run()
   at ClassicUO.Bootstrap.Main(String[] args)
######################## [START LOG] ########################
ClassicUO [STANDARD_BUILD] - 0.1.11.59 - 03/08/2023 04:14:47
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Shard: MysticalUnicornThe2ndComing.fantasyleague.cc
ClientVersion: 4.0.11c

Exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.ThrowHelper.ThrowIndexOutOfRangeException()
   at ClassicUO.Network.Huffman.DecompressChunk(Span`1 src, Int32& srcOffset, Int32 srcLength, Span`1 dest, Int32 destOffset, Int32& destLength)
   at ClassicUO.Network.NetClient.DecompressBuffer(Span`1 buffer, Int32& length)
   at ClassicUO.Network.NetClient.ProcessRecv()
   at ClassicUO.Network.NetClient.Update()
   at ClassicUO.GameController.OnNetworkUpdate()
   at ClassicUO.GameController.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.RunLoop()
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Client.Run()
   at ClassicUO.Bootstrap.Main(String[] args)
######################## [END LOG] ########################
`

**Shard**
 - Name of the shard:

**Information (please complete the following information):**
 - OS: [e.g. win7, win10, win10.17134] (just run `ver` in a command prompt) (for linux-distros `cat /etc/lsb-release`)
 - ClassicUO Version: (can be fetched from the login screen)
 - [ ] Using DEV Version?
 - Launcher: [classicuo_launcher, uof launcher, ...]

**Additional context**
 - How many clients do you run in parallel: 
 - Screen Resolution: [e.g. 1920x1080]

**Comment by andreakarasho** [comment]
pushed few fixesd during the week which should fix the decompression error.
I'll reopen the issue if you still get the exception.
